FirewallGG Integration Extension.
FAXES/faxstore-extensions pull request #7
Opened 2022-07-10 21:00 UTC by Itz-Hyperz

2022-07-10 21:01 UTC, Itz-Hyperz commented
it works, I already tested it on mine lmao.

2022-07-13 01:33 UTC, FAXES requested changes
`userId` is a string, not an integer.

We also have to review whether this extension is a secure viable option for users.

2022-07-14 06:05 UTC, FAXES commented
can be reopened at a later date.

2022-07-23 03:44 UTC, FAXES approved these changes

2022-07-23 03:44 UTC, merged